// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Query struct {
}

type Todo struct {
	ID        string    `json:"id"`
	Body      string    `json:"body"`
	CreatedOn time.Time `json:"createdOn"`
}
