service: helloworld-nodejs-lambda

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  memorySize: 128
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:GetObject"
            - "s3:DeleteObject"
          Resource:
            - !Sub "${ServerlessDeploymentBucket.Arn}/*"
        - Effect: Allow
          Action:
            - "iot:Connect"
            - "iot:DescribeEndpoint"
          Resource: "*"
        - Effect: Allow
          Action:
            - "iot:Publish"
            - "iot:Subscribe"
            - "iot:Receive"
          Resource:
            - "arn:aws:iot:*:*:topic/serverless/*"
            - "arn:aws:iot:*:*:topicfilter/serverless/*"

# layers:
#   hello:
#     path: layers/hello
#     compatibleRuntimes:
#       - nodejs18.x
#       - nodejs20.x
#     compatibleArchitectures:
#       - x86_64
#       - arm64

package:
  individually: true
  patterns:
    - "!*/**"

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    keepNames: true
    packager: pnpm

plugins:
  - serverless-live-lambda
  - serverless-esbuild

functions:
  hello:
    runtime: nodejs18.x
    handler: src/index.handler
    package:
      patterns:
        - "src/**"
