service: helloworld-nodejs-lambda

provider:
  name: aws
  region: ap-southeast-1
  memorySize: 128
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:GetObject"
            - "s3:DeleteObject"
          Resource:
            - !Sub "${ServerlessDeploymentBucket.Arn}/*"
        - Effect: Allow
          Action:
            - "iot:Connect"
            - "iot:DescribeEndpoint"
          Resource: "*"
        - Effect: Allow
          Action:
            - "iot:Publish"
            - "iot:Subscribe"
            - "iot:Receive"
          Resource:
            - "arn:aws:iot:*:*:topic/serverless/*"
            - "arn:aws:iot:*:*:topicfilter/serverless/*"

package:
  individually: true
  patterns:
    - "!*/**"

plugins:
  - serverless-live-lambda

functions:
  hello:
    runtime: nodejs18.x
    handler: app/index.handler
    package:
      patterns:
        - "app/**"
