service: graphql-apigw-go-lambda

provider:
  name: aws
  runtime: provided.al2
  region: ap-southeast-1
  memorySize: 128
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:DeleteObject'
          Resource:
            - !Sub '${ServerlessDeploymentBucket.Arn}/*'
        - Effect: Allow
          Action:
            - 'iot:Connect'
            - 'iot:DescribeEndpoint'
          Resource: '*'
        - Effect: Allow
          Action:
            - 'iot:Publish'
            - 'iot:Subscribe'
            - 'iot:Receive'
          Resource:
            - 'arn:aws:iot:*:*:topic/serverless/*'
            - 'arn:aws:iot:*:*:topicfilter/serverless/*'

custom:
  go:
    binDir: bin
    cmd: GOARCH=amd64 GOOS=linux go build -ldflags="-s -w"
    supportedRuntimes: ['provided.al2']
    buildProvidedRuntimeAsBootstrap: true

plugins:
  - serverless-go-plugin
  - serverless-live-lambda
  - serverless-better-credentials

functions:
  api:
    handler: ./cmd/api/.
    timeout: 30
    events:
      - httpApi:
          method: ANY
          path: /{proxy+}
  hello:
    handler: ./cmd/hello/.
    timeout: 30
